### ISSUE TITLE
跑demo_chat发现一个竞争点

### ISSUE THREAD

**Issue by goldpasser** [cherry-game/cherry#19]
WARNING: DATA RACE
Write at 0x00c0001ce828 by goroutine 44:
  sync/atomic.StoreInt64()
      C:/Program Files/Go/src/runtime/race_amd64.s:237 +0xb
  sync/atomic.StoreInt64()
      <autogenerated>:1 +0x15
  github.com/cherry-game/cherry/net/parser/pomelo.(*Agent).processPacket()
      D:/Workspace/gopath/pkg/mod/github.com/cherry-game/cherry@v1.3.12/net/parser/pomelo/agent.go:266 +0x2b0
  github.com/cherry-game/cherry/net/parser/pomelo.(*Agent).readChan()
      D:/Workspace/gopath/pkg/mod/github.com/cherry-game/cherry@v1.3.12/net/parser/pomelo/agent.go:166 +0x116
  github.com/cherry-game/cherry/net/parser/pomelo.(*Agent).Run.func2()
      D:/Workspace/gopath/pkg/mod/github.com/cherry-game/cherry@v1.3.12/net/parser/pomelo/agent.go:140 +0x33

Previous read at 0x00c0001ce828 by goroutine 43:
  github.com/cherry-game/cherry/net/parser/pomelo.(*Agent).writeChan()
      D:/Workspace/gopath/pkg/mod/github.com/cherry-game/cherry@v1.3.12/net/parser/pomelo/agent.go:192 +0x3a5
  github.com/cherry-game/cherry/net/parser/pomelo.(*Agent).Run.func1()
      D:/Workspace/gopath/pkg/mod/github.com/cherry-game/cherry@v1.3.12/net/parser/pomelo/agent.go:139 +0x33

Goroutine 44 (running) created at:
  github.com/cherry-game/cherry/net/parser/pomelo.(*Agent).Run()
      D:/Workspace/gopath/pkg/mod/github.com/cherry-game/cherry@v1.3.12/net/parser/pomelo/agent.go:140 +0xfc
  github.com/cherry-game/cherry/net/parser/pomelo.(*actor).defaultOnConnectFunc()
      D:/Workspace/gopath/pkg/mod/github.com/cherry-game/cherry@v1.3.12/net/parser/pomelo/actor.go:91 +0x446
  github.com/cherry-game/cherry/net/parser/pomelo.(*actor).defaultOnConnectFunc-fm()
      <autogenerated>:1 +0x47
  github.com/cherry-game/cherry/net/connector.(*Connector).Start.func1()
      D:/Workspace/gopath/pkg/mod/github.com/cherry-game/cherry@v1.3.12/net/connector/connector.go:45 +0x93

net/parser/pomelo/agent.go:192
a.lastAt没有用atomic.LoadInt64来读取

**Comment by phantacix** [comment]
已更新到master分支
