### ISSUE TITLE
demo_game_cluster中gate踢下线的问题

### ISSUE THREAD

**Issue by Rayson9418** [cherry-game/cherry#21]
在测试gate的websocket连接的时候发现一个踢下线的问题。

问题：同一个用户请求两次路由gate.user.login后，再通过这个函数 agent, ok := pomelo.GetAgentWithUID(userId)，无法获取到agent。

场景：已登录建立了websocket连接的用户，再请求这个路由gate.user.login建立新的websocket连接

原因：再次登录时会将之前的agent踢下线（会解绑用户），再重新绑定用户uid。但是踢下线操作比较费时，导致在完成了用户绑定后，又进行了解绑，使得uidMap中的uid被删除了。

规避：
![image](https://github.com/cherry-game/cherry/assets/147236346/3c289800-c3f2-4609-ace2-dd97c6d3ed39)

**Comment by sandy1219** [comment]
这个问题 应该是不会存在的，members里边已经把当前节点排除了，所以本节点并不会收到kick，后续接着Bind  没啥问题。。。
