### ISSUE TITLE
cherry/net/parser/pomelo/actor_base.go 此文件中的Broadcast方法应该将序列化操作放到内部实现

### ISSUE THREAD

**Issue by huangweiboy2** [cherry-game/cherry#22]
Broadcast 方法目前调用需要开发者自行序列化，但这是不对的，应该在方法内部实现序列化，否则开发者如果用的是protobuffer，结果不知道这个问题，直接使用json.Marshal方法序列化，会导致发送给客户端的数据，客户端无法反序列化

**Comment by phantacix** [comment]
好的，已经改成这样了。麻烦如果有问题，请再次反馈。
Broadcast(agentPath string, uidList []int64, allUID bool, route string, v interface{})
