### ISSUE TITLE
使用pomeloClient的websocket做压力测试，发现github.com\gorilla\websocket会报concurrent write to websocket connection

### ISSUE THREAD

**Issue by goldpasser** [cherry-game/cherry#24]
报错日志如下：
18:19:01.519    bot  ERROR      actor/actor_timer.go:142        concurrent write to websocket connection
github.com/cherry-game/cherry/net/actor.(*actorTimer)._updateTimer_.func2
        D:/Workspace/go-game/cherry_server_dev/cherry/net/actor/actor_timer.go:142
github.com/cherry-game/cherry/extend/utils.catchError
        D:/Workspace/go-game/cherry_server_dev/cherry/extend/utils/utils.go:19
runtime.gopanic
        C:/Program Files/Go/src/runtime/panic.go:914
github.com/gorilla/websocket.(*messageWriter).flushFrame
        D:/Workspace/gopath/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:617
github.com/gorilla/websocket.(*messageWriter).Close
        D:/Workspace/gopath/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:731
github.com/gorilla/websocket.(*Conn).beginMessage
        D:/Workspace/gopath/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:480
github.com/gorilla/websocket.(*Conn).NextWriter
        D:/Workspace/gopath/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:520
github.com/gorilla/websocket.(*Conn).WriteMessage
        D:/Workspace/gopath/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:773
github.com/cherry-game/cherry/net/connector.(*WSConn).Write
        D:/Workspace/go-game/cherry_server_dev/cherry/net/connector/ws_connector.go:141
github.com/cherry-game/cherry/net/parser/pomelo/client.(*Client).Send
        D:/Workspace/go-game/cherry_server_dev/cherry/net/parser/pomelo/client/client.go:379
github.com/cherry-game/cherry/net/parser/pomelo/client.(*Client).Request
        D:/Workspace/go-game/cherry_server_dev/cherry/net/parser/pomelo/client/client.go:138
main.(*bot).doubleBet
        D:/Workspace/go-game/cherry_server_dev/bot/double.go:88
main.(*bot).subscribeDouble.func1.2
        D:/Workspace/go-game/cherry_server_dev/bot/double.go:36
github.com/cherry-game/cherry/net/actor.(*actorTimer)._updateTimer_.func1
        D:/Workspace/go-game/cherry_server_dev/cherry/net/actor/actor_timer.go:140
github.com/cherry-game/cherry/extend/utils.Try.func1
        D:/Workspace/go-game/cherry_server_dev/cherry/extend/utils/utils.go:11
github.com/cherry-game/cherry/extend/utils.Try
        D:/Workspace/go-game/cherry_server_dev/cherry/extend/utils/utils.go:13
github.com/cherry-game/cherry/net/actor.(*actorTimer)._updateTimer_
        D:/Workspace/go-game/cherry_server_dev/cherry/net/actor/actor_timer.go:139
reflect.Value.call
        C:/Program Files/Go/src/reflect/value.go:596
reflect.Value.Call
        C:/Program Files/Go/src/reflect/value.go:380
github.com/cherry-game/cherry/net/actor.InvokeRemoteFunc.func3
        D:/Workspace/go-game/cherry_server_dev/cherry/net/actor/invoke.go:63
github.com/cherry-game/cherry/extend/utils.Try.func1
        D:/Workspace/go-game/cherry_server_dev/cherry/extend/utils/utils.go:11
github.com/cherry-game/cherry/extend/utils.Try
        D:/Workspace/go-game/cherry_server_dev/cherry/extend/utils/utils.go:13
github.com/cherry-game/cherry/net/actor.InvokeRemoteFunc
        D:/Workspace/go-game/cherry_server_dev/cherry/net/actor/invoke.go:61
github.com/cherry-game/cherry/net/actor.(*Actor).invokeFunc
        D:/Workspace/go-game/cherry_server_dev/cherry/net/actor/actor.go:224
github.com/cherry-game/cherry/net/actor.(*Actor).processRemote
        D:/Workspace/go-game/cherry_server_dev/cherry/net/actor/actor.go:158
github.com/cherry-game/cherry/net/actor.(*Actor).loop
        D:/Workspace/go-game/cherry_server_dev/cherry/net/actor/actor.go:83
github.com/cherry-game/cherry/net/actor.(*Actor).run
        D:/Workspace/go-game/cherry_server_dev/cherry/net/actor/actor.go:61

**Comment by phantacix** [comment]
已合并PR
