### ISSUE TITLE
哈希为cd0cb75529219676098d379cab2cb8c36e0fdc57的提交有bug

### ISSUE THREAD

**Issue by huangweiboy2** [cherry-game/cherry#27]
![3ff810ac0267f5048e048ac83b0f353e](https://github.com/cherry-game/cherry/assets/56343299/3b18d083-f30f-4fda-bd54-8b1bfe444fbb)

缺少message.ChanResult = make(chan interface{}) 作者记得修改

**Comment by phantacix** [comment]
已修复，改出问题了
