### ISSUE TITLE
[suggestion] cherry.go 中的startup 方法建议将服务发现和集群创建的方法调换下位置 

### ISSUE THREAD

**Issue by huangweiboy2** [cherry-game/cherry#28]
旧代码：

if app.NodeMode() == Cluster {
		cluster := ccluster.New()
		app.SetCluster(cluster)
		app.Register(cluster)

discovery := cdiscovery.New()
		app.SetDiscovery(discovery)
		app.Register(discovery)

	}

新代码：

if app.NodeMode() == Cluster {
		discovery := cdiscovery.New()
		app.SetDiscovery(discovery)
		app.Register(discovery)

		cluster := ccluster.New()
		app.SetCluster(cluster)
		app.Register(cluster)
	}

**Comment by sandy1219** [comment]
好像没有什么影响吧
